defaultFont = +1
Component.arc = 8
Component.focusWidth = 1
Button.arc = 8
Button.margin = 5,10,5,10
ToggleButton.arc = 8
TextComponent.arc = 8
TextField.margin = 4,7,4,7
ComboBox.padding = 3,7,3,7
Tree.rowHeight = 25
Tree.selectionArc = 5
Table.rowHeight = 26
Table.showHorizontalLines = false
Table.showVerticalLines = false
ScrollBar.width = 11
ScrollBar.thumbArc = 9
ScrollBar.thumbInsets = 2,2,2,2
ScrollBar.showButtons = false
TabbedPane.tabHeight = 32
TabbedPane.showTabSeparators = false
MenuItem.margin = 5,8,5,8
